language: node_js
node_js:
- '6'
- stable
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
sudo: false
cache:
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: c1af35bbf693a87ee32326641bb81342287bd80a7462a4ff3a958403f2451f1f
deploy:
  email: koike.takayuki0907@gmail.com
  provider: npm
  api_key:
    secure: n1Hpy9tNHLQp4ACIVlhO2sTC8pL8vwJkfZ3wVcZbXVBxHf4l7ctFmKGGgymTCU0LfKFKLB1xX3mZXK3UhzbkJFTZZtjJ0U5XDaZEfjfS7Mi6palpRLpRz3gGP+ixKhUzjzM2/5zpVyyYDS1dPyUKuXcRJg02k0zHQI6V9vXuNm963/tWvkpp95v+J/uV/6c4jIkDeMXMzyvGBvaxUBuQjr1iLSwOJGzVMFmJlyOqeuwpYQzJ9MMcf/MO08D/fg5mX5mo8g4hhNFvReDG15I6Bd8ZPbgWHvRZs0R1TcPeuU2LYSUxyLc2CUe8QgfFhCawK898J/RSuwXmM8806p6uR8Lh3kjwqHVLKL9lCfPuJV6vK86k1Fwpo3+IGpDDqV7bOnV6mey2PPmQxRlpLe9ihhKGKGcCUyYY17eUCsEojMj0t664O7AXz8ojCnlHC/xwBMROJLjHjGihHtDQM8Klfn8+KbLdV2JmHcMM0fwXX8OPiVlT9NZdkqOT9i8eUO965I08GOHJWy7ceBchNh2tF+YJHczJilhyH4EDvgdTRlEa4F1xGx/ZAp+QqHxuY+JKuTBFS0aBgGOiz5H+VkWzXSf67Nu8MZ1tIuJvEtR4CDYqJ8na7wMCNx9p7KkHv+BTfQyqmHbhFC0NZqtHQnX3Rt3h5EM6tE9SeRinOBeufho=
  on:
    tags: true
